#TravisCI build settings file
# For more info, see http://docs.travis-ci.com/user/getting-started/
# To validate your .travis.yml, go to http://lint.travis-ci.org/

# setting the project language
language: cpp

# setting compilers, do 2 separate sub-builds for gcc and clang
compiler:
  - g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- sudo apt-get install libtool
- sudo apt-get install autoconf

# script to run after build (run tests, etc.)
script: 
- cd initial_project/lib/mbedtls
- make clean && make 
- cd ../../.. && cd server/lib/sqlite-autoconf-3110100
- make clean && ./configure && make
- make tests && launch-tests
